app/common/EnrolmentCommon.scala, app/controllers/predicates/AuthorisedAction.scala, scalastyle-config.xml, test/controllers/LiabilityCalculationControllerSpec.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/testUtils/TestSuite.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-363
=> updated auth and tests

build.sbt, it/connectors/LiabilityCalculationConnectorISpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/models/DesErrorBodyModelSpec.scala, test/testUtils/TestSuite.scala
Updated dependancies to use play-28
[SASS-678](https://jira.tools.tax.service.gov.uk/browse/SASS-678)
=> [SASS-678] updated to use play-28

app/connectors/httpParsers/LiabilityCalculationHttpParser.scala, app/utils/PagerDutyHelper.scala, test/connectors/httpParsers/LiabilityCalculationHttpParserSpec.scala
[SASS-900](https://jira.tools.tax.service.gov.uk/browse/SASS-900)
=> [SASS-900] added connector 422/UNPROCESSSABLE ENTITY

.github/PULL_REQUEST_TEMPLATE.md
Updating the PR checklist to include checks for rebasing
https://jira.tools.tax.service.gov.uk/browse/SASS-924
=> SASS-924: Updating the PR checklist

app/connectors/DeclareCrystallisationConnector.scala, app/connectors/httpParsers/DeclareCrystallisationHttpParser.scala, app/controllers/DeclareCrystallisationController.scala, app/services/DeclareCrystallisationService.scala, conf/app.routes, it/api/DeclareCrystallisationITest.scala, it/connectors/DeclareCrystallisationConnectorISpec.scala, it/helpers/WiremockStubHelpers.scala, project/AppDependencies.scala, project/plugins.sbt, test/controllers/DeclareCrystallisationControllerSpec.scala, test/services/DeclareCrystallisationServiceSpec.scala, test/services/LiabilityCalculationServiceSpec.scala
[SASS-1025](https://jira.tools.tax.service.gov.uk/browse/SASS-865)
=> SASS-1025 - Declare crystallisation for Tax Year API

app/connectors/httpParsers/DeclareCrystallisationHttpParser.scala, it/api/DeclareCrystallisationITest.scala, project/AppDependencies.scala, project/plugins.sbt
Update DeclareCrystallisation to use v1.2.0 DES specification
[SASS-1208](https://jira.tools.tax.service.gov.uk/browse/SASS-1139)
=> SASS-1208 - Update DeclareCrystallisation to use v1.2.0 DES specification

app/config/AppConfig.scala, app/config/Modules.scala, app/connectors/httpParsers/DeclareCrystallisationHttpParser.scala, it/connectors/DeclareCrystallisationConnectorISpec.scala, it/connectors/LiabilityCalculationConnectorISpec.scala, project/AppDependencies.scala, test/config/MockAppConfig.scala, test/connectors/httpParsers/DESParserSpec.scala, test/testUtils/TestSuite.scala
Removing injection from unit tests
[SASS-739](https://jira.tools.tax.service.gov.uk/browse/SASS-739)
=> [SASS-1614] - removing injection from unit tests

app/connectors/GetCalculationListConnector.scala, app/connectors/httpParsers/GetCalculationListHttpParser.scala, app/models/GetCalculationListModel.scala, it/connectors/GetCalculationListConnectorISpec.scala, test/connectors/httpParsers/GetCalculationListHttpParserSpec.scala, test/models/GetCalculationsListResponseSpec.scala
Creating a Connector for API1404
(https://jira.tools.tax.service.gov.uk/browse/MISUV-2893)
=> MISUV-2893: Create a Connector for API1404

app/connectors/CalculationDetailsConnector.scala, app/connectors/httpParsers/CalculationDetailsHttpParser.scala, it/assets/GetCalculationDetailsConstants.scala, it/connectors/CalculationDetailsConnectorISpec.scala, test/connectors/httpParsers/CalculationDetailsHttpParserSpec.scala, test/models/liabilitycalculation/LiabilityCalculationResponseModelSpec.scala, test/testConstants/GetCalculationDetailsConstants.scala
=> MISUV-2894 added connector to API 1523 get tax calculations

app/config/AppConfig.scala, app/connectors/CalculationDetailsConnector.scala, app/connectors/GetCalculationListConnector.scala, app/connectors/IFConnector.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/connectors/CalculationDetailsConnectorISpec.scala, it/connectors/GetCalculationListConnectorISpec.scala, test/config/MockAppConfig.scala, test/models/liabilitycalculation/LiabilityCalculationResponseModelSpec.scala, test/services/GetCalculationDetailsServiceSpec.scala
=> MISUV-2903 added service layer to get calculation details

app/connectors/httpParsers/CalculationDetailsHttpParser.scala, app/controllers/CalculationDetailController.scala, app/models/calculation/AllowancesAndDeductions.scala, app/models/calculation/Calculation.scala, app/models/calculation/CalculationResponseModel.scala, app/models/calculation/Reliefs.scala, app/models/calculation/TaxDeductedAtSource.scala, app/models/calculation/taxcalculation/CapitalGainsTax.scala, app/models/calculation/taxcalculation/IncomeTax.scala, app/models/calculation/taxcalculation/Nics.scala, app/models/calculation/taxcalculation/TaxCalculation.scala, conf/app.routes, it/assets/GetCalculationDetailsConstants.scala, test/controllers/CalculationDetailControllerSpec.scala, test/models/calculation/CalculationResponseModelModelSpec.scala, test/testConstants/GetCalculationDetailsConstants.scala
Creating route and controller.
=> MISUV-2904: [ITC-BE] Create Calculation routes

test/connectors/IFConnectorSpec.scala
Improving test coverage on income-tax-calcuation repo
=> Improve coverage on income-tax-calcuation repo

app/connectors/GetCalculationListConnector.scala, app/controllers/CalculationDetailController.scala, it/connectors/GetCalculationListConnectorISpec.scala
=> Fix get calc list connector

app/connectors/GetCalculationListConnector.scala, conf/application.conf, it/connectors/GetCalculationListConnectorISpec.scala
=> Pointing to DES for 1404 from IF

app/models/calculation/Calculation.scala, app/models/calculation/EndOfYearEstimate.scala, it/assets/GetCalculationDetailsConstants.scala, test/resources/liabilityResponsePruned.json, test/testConstants/GetCalculationDetailsConstants.scala
=> Misuv 3135 forecast fields

app/models/calculation/CalculationResponseModel.scala, it/assets/GetCalculationDetailsConstants.scala, test/models/ExampleCalculationSpec.scala, test/models/calculation/CalculationResponseModelModelSpec.scala, test/testConstants/GetCalculationDetailsConstants.scala
Added optional type to calculationTimestamp Parameter
=> SASS-patch2 : Added optional type to calculationTimestamp Parameter

app/models/calculation/CalculationResponseModel.scala, it/assets/GetCalculationDetailsConstants.scala, test/models/calculation/CalculationResponseModelModelSpec.scala, test/resources/liabilityResponsePruned.json, test/testConstants/GetCalculationDetailsConstants.scala
https://jira.tools.tax.service.gov.uk/browse/MISUV-3200
=> MISUV-3200 - Added calculationReason to Metadata in CalculationResponseModel

app/connectors/httpParsers/GetBusinessDetailsHttpParser.scala, app/controllers/TaxYearsDataController.scala, app/services/GetBusinessDetailsService.scala, app/services/GetTaxYearsDataService.scala, it/connectors/GetBusinessDetailsConnectorISpec.scala, test/controllers/TaxYearsDataControllerSpec.scala, test/services/GetBusinessDetailsServiceSpec.scala, test/services/GetTaxYearsDataServiceSpec.scala
=> Updated to handle 404

README.md
[SASS-2969](https://jira.tools.tax.service.gov.uk/browse/SASS-2935)
=> SASS-2969 : Updated Income Tax Calculation Readme

it/api/CalculationDetailsITest.scala, it/api/DeclareCrystallisationITest.scala, it/api/GetLiabilityCalculationIdITest.scala, project/AppDependencies.scala
[SASS-2960](https://jira.tools.tax.service.gov.uk/browse/SASS-2960)
=> SASS-2960 Update bootstrap-BE/FE-play-28 dependencies

project/AppDependencies.scala
Update dependencies in income-tax-calculation to the latest versions.
[SASS-3230](https://jira.tools.tax.service.gov.uk/browse/SASS-3230)
=> SASS-3230: Update dependencies in income-tax-calculation

app/connectors/httpParsers/CalculationDetailsHttpParser.scala, app/connectors/httpParsers/DESParser.scala, app/connectors/httpParsers/GetBusinessDetailsHttpParser.scala, app/connectors/httpParsers/GetCalculationListHttpParser.scala, app/connectors/httpParsers/LiabilityCalculationHttpParser.scala, it/connectors/GetCalculationListConnectorISpec.scala, test/connectors/httpParsers/CalculationDetailsHttpParserSpec.scala, test/connectors/httpParsers/DESParserSpec.scala, test/connectors/httpParsers/GetBusinessDetailsHttpParserSpec.scala, test/connectors/httpParsers/GetCalculationListHttpParserSpec.scala, test/connectors/httpParsers/LiabilityCalculationHttpParserSpec.scala
Added extra logging around json parser errors to diagnose a prod issue.
https://jira.tools.tax.service.gov.uk/browse/MISUV-3824
=> Misuv 4058 tax calc bug

app/connectors/CalculationDetailsConnector.scala, app/connectors/CalculationDetailsConnectorLegacy.scala, app/connectors/httpParsers/DESParser.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/connectors/CalculationDetailsConnectorISpec.scala, it/connectors/CalculationDetailsConnectorLegacyISpec.scala, test/controllers/TaxYearsDataControllerSpec.scala, test/services/GetCalculationDetailsServiceSpec.scala, test/services/GetTaxYearsDataServiceSpec.scala, test/testConstants/IncomeSourceDetailsTestConstants.scala
Create a new CalculationDetailsConnector to call 1885 API. And rename the existing  CalculationDetailsConnector to CalculationDetailsConnectorLegacy for 1523
[Create a new connector MISUV-4157](https://jira.tools.tax.service.gov.uk/browse/MISUV-4157)
=> MISUV-4157 Create a new connector

app/models/calculation/EndOfYearEstimate.scala
=> Misuv 3916

app/controllers/CalculationDetailController.scala, app/controllers/TaxYearsDataController.scala, app/controllers/predicates/AuthorisedAction.scala, conf/logback.xml
Make sure classes which use debug log statements get logged.
[SASS-3823](https://jira.tools.tax.service.gov.uk/browse/SASS-3823)
=> SASS-3823: Update logging in calculation BE

app/controllers/LiabilityCalculationController.scala
=> MISUV 4302: Log Calc API Error Reason

app/models/calculation/taxcalculation/TaxCalculation.scala
=> MISUV-4353: Added totalIncomeTaxAndNicsAndCgt to TaxCalculation model

app/config/AppConfig.scala, app/controllers/predicates/AuthorisedAction.scala, conf/application.conf, it/helpers/AuthStubs.scala, test/config/MockAppConfig.scala, test/controllers/predicates/AuthorisedActionSpec.scala, test/testUtils/TestSuite.scala
=> MISUV-4449 : Move Confidence Level property to config - calc component

app/connectors/httpParsers/DESParser.scala, app/controllers/predicates/AuthorisedAction.scala, app/repositories/TaxYearsDataRepositoryImpl.scala, build.sbt, it/api/CalculationDetailsITest.scala, it/api/GetLiabilityCalculationIdITest.scala, it/connectors/GetCalculationListConnectorISpec.scala, it/repositories/TaxYearsDataRepositoryISpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/connectors/httpParsers/CalculationDetailsHttpParserSpec.scala, test/connectors/httpParsers/DESParserSpec.scala, test/connectors/httpParsers/GetBusinessDetailsHttpParserSpec.scala, test/connectors/httpParsers/GetCalculationListHttpParserSpec.scala, test/connectors/httpParsers/LiabilityCalculationHttpParserSpec.scala, test/services/GetTaxYearsDataServiceSpec.scala, test/testUtils/SecureGCMCipherSpec.scala
Upgrade income-tax-calculation to Scala 2.13.8 
[MISUV-4250](https://jira.tools.tax.service.gov.uk/browse/MISUV-4250)
=> MISUV-4517 Upgrade to Scala 2.13.x - income-tax-calculation

README.md
=> Test PR - ncome-tax-calculation

app/connectors/GetCalculationListConnector.scala, app/connectors/GetCalculationListConnectorLegacy.scala, app/connectors/httpParsers/GetCalculationListHttpParserLegacy.scala, app/models/GetCalculationListModel.scala, app/models/GetCalculationListModelLegacy.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/api/CalculationDetailsITest.scala, it/connectors/GetCalculationListConnectorISpec.scala, it/connectors/GetCalculationListConnectorLegacyISpec.scala, test/connectors/httpParsers/GetCalculationListHttpParserLegacySpec.scala, test/models/GetCalculationsListResponseSpec.scala, test/services/GetCalculationDetailsServiceSpec.scala
Add get calculation list connector for new tax year API.
[SASS-3551](https://jira.tools.tax.service.gov.uk/browse/SASS-3551)
=> SASS-3551: API#1896 (for tax year 23-24) and API#1404 Integration - Tax year specific API changes

app/utils/TaxYear.scala, test/testUtils/TaxYearSpec.scala
* change taxYear format to YY-YY as per spec;
=> MISUV-4735: changes taxYear format to YY-YY 

app/models/calculation/taxcalculation/TaxCalculation.scala
=> Misuv 4864 cl279

build.sbt
=> MISUV-4887: disable JUnitXmlReportPlugin

app/connectors/DeclareCrystallisationConnector.scala, conf/application.conf, it/api/DeclareCrystallisationITest.scala, it/connectors/DeclareCrystallisationConnectorISpec.scala, test/services/GetTaxYearsDataServiceSpec.scala
=> retire API 1416 change to 1780

app/config/AppConfig.scala, app/connectors/GetBusinessDetailsConnector.scala, conf/application.conf, test/config/MockAppConfig.scala
=> add useBusinessDetailsStub switch

conf/application.conf
=> Sass use business details stub

app/services/GetCalculationDetailsService.scala, app/services/LiabilityCalculationService.scala, app/utils/TaxYear.scala, it/connectors/PostCalculateIncomeTaxLiabilityConnectorISpec.scala, project/AppDependencies.scala, project/plugins.sbt, test/services/GetCalculationDetailsServiceSpec.scala, test/services/LiabilityCalculationServiceSpec.scala
[SASS-5051](https://jira.tools.tax.service.gov.uk/browse/SASS-5051)
=> SASS-5051 Implement TYS APIs to handle future tax years

app/models/calculation/Calculation.scala, it/assets/GetCalculationDetailsConstants.scala, test/resources/liabilityResponseArrayTest.json, test/resources/liabilityResponsePruned.json, test/testConstants/GetCalculationDetailsConstants.scala
=> MISUV-5970 Add other income field

app/connectors/httpParsers/CalculationDetailsHttpParser.scala
* log json parsing response: temp code
=> MISUV-6574: add logging 

app/connectors/httpParsers/APIParser.scala, app/connectors/httpParsers/CalculationDetailsHttpParser.scala, test/connectors/httpParsers/CalculationDetailsHttpParserSpec.scala
=> Misuv 6574 add logging v2

app/connectors/CalculationDetailsConnector.scala, app/connectors/httpParsers/APIParser.scala, app/connectors/httpParsers/CalculationDetailsHttpParser.scala, app/models/GetCalculationListModel.scala, it/api/CalculationDetailsITest.scala, it/connectors/CalculationDetailsConnectorISpec.scala, it/connectors/GetCalculationListConnectorISpec.scala, test/connectors/httpParsers/CalculationDetailsHttpParserSpec.scala, test/services/GetCalculationDetailsServiceSpec.scala
* revert last changes: adding http response body to error details;
* add logging around 1885 call;
=> MISUV-6574: add logging around 1885 call

app/connectors/CalculationDetailsConnector.scala, app/connectors/GetCalculationListConnector.scala, it/connectors/CalculationDetailsConnectorISpec.scala
* **add logging around 1885 and 1896 calls;
* fix broken it:tests;**
=> MISUV-6574: fix broken it:Tests

app/models/calculation/Reliefs.scala, app/models/calculation/taxcalculation/IncomeTax.scala, it/assets/GetCalculationDetailsConstants.scala, test/resources/liabilityResponsePruned.json, test/testConstants/GetCalculationDetailsConstants.scala
=> MISUV-6649: Add Basic rate divergence

app/connectors/GetCalculationListConnector.scala, app/connectors/httpParsers/CalculationDetailsHttpParser.scala, app/connectors/httpParsers/GetCalculationListHttpParser.scala, app/connectors/httpParsers/GetCalculationListHttpParserLegacy.scala, it/api/CalculationDetailsITest.scala, it/connectors/CalculationDetailsConnectorISpec.scala, it/connectors/CalculationDetailsConnectorLegacyISpec.scala
=> MISUV-6743: Changed NOT_FOUND to NO_CONTENT to avoid pager duty log

app/connectors/httpParsers/CalculationDetailsHttpParser.scala, app/models/mongo/LocalDateExtensions.scala, app/models/mongo/LocalDateJsonExtensions.scala, app/models/mongo/TaxYearsData.scala, app/repositories/TaxYearsDataRepositoryImpl.scala, app/services/GetTaxYearsDataService.scala, app/utils/Clock.scala, build.sbt, conf/application.conf, conf/prod.routes, it/repositories/TaxYearsDataRepositoryISpec.scala, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/models/mongo/TaxYearsDataSpec.scala, test/testUtils/TestSuite.scala, test/testUtils/TestingClock.scala
Here is migration guide:
https://docs.google.com/document/d/1LpahhQNmb7XMqOFp0_aAnKgrnTzA26XwdwpceQdx_ak/edit#heading=h.tgal7v8lebmw
Note:
* as per instruction in the migration guide we have to move away from "Joda time" type =>
`Joda time is no longer provided transitively by Play 2.9/3.0 and similarly not supported by  hmrc-mongo built for Play 2.9/3.0. If you are still using Joda time, please replace this with Java time.`
* we are would remain on the next version of Scala for the time been: "2.13.8"
=> Misuv-7039: Upgrade to Play 3.0

app/config/AppConfig.scala, app/connectors/PostCalculateIncomeTaxLiabilityConnector.scala, project/plugins.sbt, test/services/GetTaxYearsDataServiceSpec.scala
Fix API 1897 returning 400.
Some tests were preventing the build so fixed those also.
=> SASS-8081: Fix API 1897, fix tests preventing build

app/connectors/LiabilityCalculationConnector.scala, app/connectors/PostCalculateIncomeTaxLiabilityConnector.scala, conf/app.routes, it/test/api/GetLiabilityCalculationIdITest.scala, it/test/connectors/LiabilityCalculationConnectorISpec.scala, it/test/connectors/PostCalculateIncomeTaxLiabilityConnectorISpec.scala, project/AppDependencies.scala, project/build.properties, project/plugins.sbt
send crystallise as false for inYear estimate.
=> SASS-8359: allow crystallise to be sent as false

app/connectors/CalculationDetailsConnector.scala, app/connectors/CalculationDetailsConnectorLegacy.scala, app/connectors/DesConnector.scala, app/connectors/GetCalculationListConnector.scala, app/connectors/GetCalculationListConnectorLegacy.scala, app/connectors/IFConnector.scala, it/test/api/CalculationDetailsITest.scala
Reverts hmrc/income-tax-calculation#104
=> Revert "Sass 8319 - calculation not populating after 404 - implemented retry"

app/config/AppConfig.scala, app/connectors/DesConnector.scala, app/connectors/GetCalculationListConnectorLegacy.scala, app/connectors/IFConnector.scala, conf/application.conf, it/test/connectors/GetCalculationListConnectorLegacyISpec.scala, test/config/MockAppConfig.scala
=> MISUV-7751 Migrate API#1404 (Get Calc List) to IF Platform for R13

app/config/AppConfig.scala, check.sh, conf/application.conf, it/test/helpers/WiremockSpec.scala
Requested here - https://github.com/hmrc/app-config-qa/pull/24190
=> SASS-10720 Added feature-switch flag to useBusinessDetailsStub and useEncryption

app/common/EnrolmentCommon.scala, app/config/AppConfig.scala, app/controllers/predicates/AuthorisedAction.scala, conf/application.conf, project/AppDependencies.scala, project/plugins.sbt, test/common/EnrolmentCommonSpec.scala, test/config/MockAppConfig.scala, test/controllers/predicates/AuthorisedActionSpec.scala
[SASS-11000](https://jira.tools.tax.service.gov.uk/browse/SASS-11000)
=> SASS-11303 - disable multi agent authentication

app/config/AppConfig.scala, test/config/MockAppConfig.scala
* remove hip/env~ configuration settings
=> MISUV-9483: clean up

app/connectors/GetCalculationListConnector.scala, app/connectors/httpParsers/GetCalculationListHttpParser.scala, app/models/GetCalculationListModel.scala, app/services/GetCalculationDetailsService.scala, app/services/LiabilityCalculationService.scala, app/utils/SecureGCMCipher.scala, app/utils/TaxYear.scala, conf/application.conf, it/test/connectors/GetCalculationListConnectorISpec.scala, it/test/connectors/PostCalculateIncomeTaxLiabilityConnectorISpec.scala, it/test/helpers/CalculationDetailsITestHelper.scala, test/services/GetCalculationDetailsServiceSpec.scala, test/services/LiabilityCalculationServiceSpec.scala, test/testUtils/TestSuite.scala
=> MISUV-9623 added logic for calculation list for 25-26 tax year onwards

app/models/calculation/CalculationResponseModel.scala, app/models/hip/CalculationResponseModel.scala, app/models/hip/calculation/AllowancesAndDeductions.scala, app/models/hip/calculation/EndOfYearEstimate.scala, conf/application.conf, it/test/assets/GetCalculationDetailsConstants.scala, it/test/constants/HipGetCalculationDetailsConstants.scala, test/models/calculation/CalculationResponseModelModelSpec.scala, test/resources/liabilityResponseArrayTest.json, test/resources/liabilityResponsePruned.json, test/testConstants/GetCalculationDetailsConstants.scala
Updating the model for the new HIP API GetCalculationsData to include the 'calculationType' field in the metadata object. 
Also updating 'post-cessationTradeReceipts' to use correct field for reads/writes and updating the type of 'totalAllowancesAndDeductions' in the EndOfYearEstimate object to have the correct type which matches the schema.
=> MISUV-9783 Adding calculationType field to metadata object 

app/config/AppConfig.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/test/api/CalculationDetailsHipITest.scala, test/config/MockAppConfig.scala
Migration of legacy GetCalculationData (#1523) to HIP version
=> MISUV-9952 Migrate API#1523 to Hip version

app/config/AppConfig.scala, app/connectors/GetCalculationListConnector.scala, app/connectors/hip/HipGetCalculationListConnector.scala, app/connectors/httpParsers/APIParser.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/test/api/CalculationDetailsHipITest.scala, it/test/api/CalculationDetailsITest.scala, it/test/connectors/HipGetCalculationListConnectorISpec.scala, test/config/MockAppConfig.scala, test/services/GetCalculationDetailsServiceSpec.scala
=> MISUV 10088

app/connectors/GetCalculationListConnector.scala, app/services/GetCalculationDetailsService.scala, conf/application.conf, it/test/api/CalculationDetailsITest.scala, it/test/connectors/GetCalculationListConnectorISpec.scala, it/test/helpers/CalculationDetailsITestHelper.scala, test/services/GetCalculationDetailsServiceSpec.scala
=> [MISUV-10190] Replacing API 1896 with 2150
